name       : firejail
version    : 0.9.42
release    : 1
source     :
    - https://github.com/netblue30/firejail/archive/0.9.42.tar.gz : 5a604f6189e80d4ad35de9497e9623c8e6c8f624c5edd02844bc9f9acace5217
license    : GPL-2.0
component  : security
summary    : Firejail is a SUID sandbox program
description: |
    Firejail is a SUID sandbox program that reduces the risk of security breaches by restricting the running environment of  untrusted  applications
builddeps  :
    - gcc
setup      : |
    sed -i "s|sysconfdir=\"/etc\"|sysconfdir=\"/usr/share/defaults/firejail\"|" configure
    %configure
build      : |
    %make
install    : |
    %make_install
