name       : firejail
version    : 0.9.60
release    : 9
source     :
    - https://github.com/netblue30/firejail/archive/0.9.60.tar.gz : dd3059b19365c2c095b85e3f86737fdcaca0a05357680f0e377bebf07791bc70
license    : GPL-2.0-or-later
component  : security
summary    : Sandbox your applications
description: |
    Firejail is a SUID sandbox program that reduces the risk of security breaches by restricting the running environment of untrusted applications. It allows a process and all its descendants to have their own private view of the globally shared kernel resources, such as the network stack, process table, mount table.
builddeps  :
    - pkgconfig(libapparmor) # Tests
    - expect                 # Tests
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-Fix-appimage-on-linux-5.4.x-kernel.patch
    %reconfigure --enable-apparmor
build      : |
    %make
install    : |
    %make_install
    # Remove README, license file etc.
    rm -rf $installdir/usr/share/doc
check      : |
    %make test
